apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  -  name: webserver
     image: nginx:latest
     ports:
     -  containerPort: 8080
  -  name: webwatcher
     image: afakharany/watcher:latest